package view;

import controler.ManipularArquivoControl;
import controler.VendaControl;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.Produto;
import model.Venda;

/**
 *
 * @author chris
 */
public class TelaPrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalView
     */
    ArrayList<Produto> lista = new ArrayList<>();
    ArrayList<Venda> listaVenda = new ArrayList<>();
    private int id=0;

    public TelaPrincipalView() {

        initComponents();
        preencheLista();
    }

    public void preencheLista() {

        Produto p = new Produto(1, "Uva", 2.56);
        Produto p2 = new Produto(2, "Pera", 3.56);
        Produto p3 = new Produto(3, "Coca", 5);
        Produto p4 = new Produto(4, "Maça", 4.5);

        lista.add(p);
        lista.add(p2);
        lista.add(p3);
        lista.add(p4);

        DefaultListModel dlm = new DefaultListModel();
        for (int i = 0; i < this.lista.size(); i++) {
            dlm.addElement(lista.get(i).getNome() + " - " + lista.get(i).getPreco());
        }
        jList1.setModel(dlm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Produtos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, 150));

        jLabel2.setText("Quantidade");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 142, -1));

        jButton1.setText("Adicionar Produto");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 532, 146));

        jLabel3.setText("Carrinho");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        jButton2.setText("Limpar Carrinho");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, -1, -1));

        jButton3.setText("Remover");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, -1, -1));

        jButton4.setText("Exportar em PDF");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        jButton5.setText("Exportar em TXT");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, -1, -1));

        jLabel4.setText("Numero do item");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 95, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        for (int i = 0; i < lista.size(); i++) {
            if (this.jList1.getSelectedValue().contains(this.lista.get(i).getNome())) {

                VendaControl venda = new VendaControl(this.listaVenda);

                if (this.jTextField1.getText().length() > 0) {
                    venda.addVenda(id, this.lista.get(i).getNome(), this.lista.get(i).getPreco(), Integer.parseInt(this.jTextField1.getText()));
                } else {
                    venda.addVenda(id, this.lista.get(i).getNome(), this.lista.get(i).getPreco(), 1);
                }
                this.listaVenda = venda.getVendas();
                id++;

                String reallyLongString = "";

                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
                LocalDateTime now = LocalDateTime.now();
                reallyLongString = "Mercado \nData: " + dtf.format(LocalDateTime.now()) + "\n\n"
                        + "Item       Descrição           Qtd         Valor Unitário          Valor Total\n";

                for (Venda produto : venda.getVendas()) {
                    reallyLongString += "\n" + produto.getId()
                            + "              " + produto.getNome()
                            + "                " + String.valueOf(produto.getQtd())
                            + "                " + String.valueOf(produto.getPreco())
                            + "                  " + String.valueOf(produto.getQtd() * produto.getPreco());
                }

                this.jTextArea1.setText(reallyLongString);

            }
        }

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked

        VendaControl venda = new VendaControl(listaVenda);

        if (this.jTextField2.getText().length() > 0) {
            venda.removeVenda(Integer.parseInt(this.jTextField2.getText()));
            this.listaVenda = venda.getVendas();
            String reallyLongString = "";

            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
            LocalDateTime now = LocalDateTime.now();
            reallyLongString = "Mercado \nData: " + dtf.format(LocalDateTime.now()) + "\n\n"
                    + "Item       Descrição           Qtd         Valor Unitário          Valor Total\n";

            for (Venda produto : venda.getVendas()) {
                reallyLongString += "\n" + produto.getId()
                        + "              " + produto.getNome()
                        + "                " + String.valueOf(produto.getQtd())
                        + "                " + String.valueOf(produto.getPreco())
                        + "                  " + String.valueOf(produto.getQtd() * produto.getPreco());
            }

            this.jTextArea1.setText(reallyLongString);
        } else {
            JOptionPane.showMessageDialog(null, "Escolha o numero do produto", "Não foi possivel remover", HEIGHT);
        }


    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        VendaControl venda = new VendaControl(this.listaVenda);
        venda.removeAll();
        this.listaVenda = venda.getVendas();

        this.jTextArea1.setText("");
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
       ManipularArquivoControl manipularArquivo = new ManipularArquivoControl();
       String conteudo = this.jTextArea1.getText();
        try {
            manipularArquivo.arquivoSalvarTxt(conteudo);
            JOptionPane.showMessageDialog(null, "Arquivo salvo na raiz do projeto");
        
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TelaPrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
      ManipularArquivoControl manipularArquivo = new ManipularArquivoControl();
      double total = 0;
        for (Venda produto : listaVenda) {
             total +=  produto.getQtd()* produto.getPreco();

        }
        try {
            manipularArquivo.arquivoPDF(listaVenda,total);
             JOptionPane.showMessageDialog(null, "Arquivo salvo na raiz do projeto");
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
